name: Analyze Templates

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build Go application
        working-directory: src
        run: go build -o ../azdt

      - name: Sync Templates
        run: ./azdt sync -o templates

      - name: Analyze Templates
        run: ./azdt analyze -f templates -o output

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Analysis (${{ env.NOW }})
          tag_name: analysis-${{ github.run_number }}
          body_path: output/output.md
          draft: false
          prerelease: false
          make_latest: true
          files: output/**/*
